name: C Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build
        run: make cat

      - name: Run Checks
        run: make check

      - name: Clean
        if: always()
        run: make clean
