name: C Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build program
        run: make cat

      - name: Run tests
        run: make test

      - name: Clean up
        run: make clean
